# -*- coding: utf-8 -*-
"""
engines/_paper_generic.py
─────────────────────────
임의 물성용 일반 논문 템플릿.

PropertyConfig.domain / display_name / unit / direction 같은 메타데이터를
사용해서 도메인-중립 논문 초안을 생성한다.  실제 수치는 모두 학습/스크리닝
결과에서 추출하며 LLM 생성 텍스트는 사용하지 않는다.
"""
from __future__ import annotations

import io
from datetime import date

import numpy as np
import pandas as pd


# ─────────────────────────────────────────────────────────────────────────────
def _direction_phrase(cfg) -> str:
    if cfg.direction == "lower_better":
        return f"{cfg.display_name} 값이 **낮을수록** 우수한 후보"
    if cfg.direction == "higher_better":
        return f"{cfg.display_name} 값이 **높을수록** 우수한 후보"
    return f"{cfg.display_name} 값이 목표 구간 안에 들어오는 후보"


def _good_phrase(cfg) -> str:
    op = "<" if cfg.direction == "lower_better" else ">"
    return f"{cfg.target_column} {op} {cfg.screening_threshold:g}"


def generate_paper(
    cfg,                              # PropertyConfig
    df_dataset:   pd.DataFrame,
    feat_names:   list[str],
    X_all_shape:  tuple,
    cv_result:    dict,
    metrics:      dict,
    df_screening: pd.DataFrame,
    feat_imp:     pd.Series,
    log_tf:       bool = True,
    best_model:   str  = "gbr",
    model_mode:   str  = "full",
    **_ignored,
) -> dict:
    today  = date.today().strftime("%Y-%m-%d")
    target = cfg.target_column
    unit   = cfg.unit or "-"

    # ── 데이터셋 통계 ─────────────────────────────────────────────────────────
    n_total = len(df_dataset)
    y_min   = df_dataset[target].min()
    y_max   = df_dataset[target].max()
    y_mean  = df_dataset[target].mean()
    y_med   = df_dataset[target].median()
    n_good  = int(cfg.is_good(df_dataset[target]).sum())

    # ── 모델 성능 ─────────────────────────────────────────────────────────────
    bm     = best_model.lower()
    bm_tr  = metrics.get(bm, {}).get("train", {})
    bm_te  = metrics.get(bm, {}).get("test",  {})
    cv_r2  = cv_result.get("r2_mean", 0.0)
    cv_std = cv_result.get("r2_std",  0.0)
    cv_rmse= cv_result.get("rmse_mean", 0.0)

    # ── 피처 ──────────────────────────────────────────────────────────────────
    top5     = feat_imp.head(5)
    top5_str = ", ".join(f"{n}({v:.3f})" for n, v in top5.items())
    n_raw    = X_all_shape[1]
    n_sel    = len(feat_names)

    # ── 스크리닝 ──────────────────────────────────────────────────────────────
    df_valid = (df_screening[df_screening["valid"] == True]
                if "valid" in df_screening.columns else df_screening)
    n_cand   = len(df_valid)
    if "pred_mean" in df_valid.columns and n_cand:
        n_good_pred = int(cfg.is_good(df_valid["pred_mean"]).sum())
    else:
        n_good_pred = 0
    n_ad_ok = int(df_valid["ad_ok"].sum()) if "ad_ok" in df_valid.columns else 0

    # ── 본문 ──────────────────────────────────────────────────────────────────
    title = f"QSPR 기반 {cfg.display_name} 예측 및 후보 분자 스크리닝"
    header = (
        f"# {title}\n\n"
        f"*Generated by MIDAS_v02 · {today}*\n\n"
        f"**Property:** {cfg.display_name} ({target}, {unit})  \n"
        f"**Domain:** {cfg.domain}  \n"
        f"**Best model:** {best_model.upper()}  ·  "
        f"**Mode:** {model_mode}  ·  "
        f"**log-transform:** {log_tf}\n\n"
    )

    abstract = (
        "## Abstract\n"
        f"본 연구는 {cfg.domain}을 응용 도메인으로, "
        f"분자 구조에서 직접 계산 가능한 RDKit 기술자({n_raw}개 → {n_sel}개 선택) "
        f"기반 QSPR 모델로 **{cfg.display_name}**을 예측한다. "
        f"총 {n_total}개 분자({target} 범위 {y_min:.2f}~{y_max:.2f}, 중앙값 {y_med:.2f}) "
        f"를 사용하여 GBR·RF·Ridge·GPR 4종을 학습하고 CV R²로 최적 모델을 선택했다. "
        f"최적 모델 {best_model.upper()}는 5-fold CV R² = "
        f"{cv_r2:.3f} ± {cv_std:.3f}, Test R² = {bm_te.get('R2',0):.3f} "
        f"(RMSE = {bm_te.get('RMSE',0):.3f}) 성능을 보였다. "
        f"스크리닝 단계에서 {n_cand}개 후보 분자 중 기준({_good_phrase(cfg)})을 "
        f"만족하는 분자는 {n_good_pred}개로 예측되었고, 이 중 "
        f"학습 데이터의 적용가능역(AD) 안에 있는 분자는 {n_ad_ok}개였다.\n\n"
    )

    intro = (
        "## 1. Introduction\n"
        f"{cfg.domain} 분야에서 {cfg.display_name}({target}) 은 핵심 성능 지표 중 "
        f"하나이다. {_direction_phrase(cfg)}로 평가된다. "
        "실험 기반 측정은 분자 합성·시료 정제·계측 등에 많은 자원을 요구하므로, "
        "분자 구조 정보만으로 빠르게 후보를 거를 수 있는 QSPR(정량적 구조-물성 관계) "
        "모델의 가치가 크다. 본 연구는 RDKit 분자 기술자와 사이킷런 회귀 모델만으로 "
        "재현 가능한 파이프라인(`random_state=42` 전체 고정)을 구축하고, "
        "응용 도메인에 적합한 분자를 스크리닝하는 워크플로우를 제시한다.\n\n"
    )

    methods = (
        "## 2. Methods\n"
        f"### 2.1 Dataset\n"
        f"- 총 분자 수: {n_total}\n"
        f"- {target} 범위: {y_min:.2f} ~ {y_max:.2f} ({unit})\n"
        f"- 평균/중앙값: {y_mean:.2f} / {y_med:.2f}\n"
        f"- 기준({_good_phrase(cfg)}) 만족 분자: {n_good}개\n\n"
        f"### 2.2 Features\n"
        f"RDKit 내장 기술자 + 원자 카운트 커스텀 기술자 총 **{n_raw}개**를 계산 후, "
        f"3단계 필터(분산 0 제거 → |corr|>0.95 제거 → RandomForest 중요도 Top-N)로 "
        f"**{n_sel}개**를 선택했다.\n\n"
        f"### 2.3 Models\n"
        f"GBR, RandomForest, Ridge, GaussianProcess(Matern 2.5) 4종을 동일 분할에서 "
        f"학습하고, 5-fold CV R² 가 가장 높은 모델을 최종 모델로 자동 선택했다. "
        f"학습 시 log-transform: **{log_tf}**, stratified split으로 train/val/test = "
        f"70/15/15 비율 사용. 모든 random_state=42 고정.\n\n"
        f"### 2.4 Applicability Domain\n"
        f"Williams plot 기반 leverage (h*) 로 스크리닝 분자가 학습 데이터 분포 안에 "
        f"있는지 판정.\n\n"
    )

    results = (
        "## 3. Results\n"
        f"### 3.1 Selected Features (Top-5)\n"
        f"{top5_str}\n\n"
        f"### 3.2 Best Model Performance\n"
        f"- **Model:** {best_model.upper()}\n"
        f"- **5-fold CV R²:** {cv_r2:.3f} ± {cv_std:.3f}\n"
        f"- **CV RMSE:** {cv_rmse:.3f} ({unit})\n"
        f"- **Train R²:** {bm_tr.get('R2',0):.3f}  ·  "
        f"**Test R²:** {bm_te.get('R2',0):.3f}\n"
        f"- **Test RMSE:** {bm_te.get('RMSE',0):.3f}  ·  "
        f"**Test MAE:** {bm_te.get('MAE',0):.3f}\n\n"
        f"### 3.3 Screening\n"
        f"- 후보 분자: {n_cand}개\n"
        f"- 기준({_good_phrase(cfg)}) 만족 예측: {n_good_pred}개\n"
        f"- AD 내부: {n_ad_ok}개\n\n"
    )

    conclusion = (
        "## 4. Conclusion\n"
        f"본 연구는 {cfg.display_name} 예측을 위한 재현 가능한 QSPR 파이프라인을 "
        f"제시하고, {n_cand}개 후보 중 {n_good_pred}개의 우수 후보를 확보했다. "
        f"향후 연구로는 데이터셋 확장, 도메인 전용 기술자 도입, "
        f"실험적 검증 등을 고려할 수 있다.\n\n"
    )

    limitations = (
        "## 5. Limitations\n"
        f"- 데이터셋 크기({n_total}개)는 도메인에 따라 충분치 않을 수 있음.\n"
        f"- 단일 측정 조건(온도/주파수 등) 가정. 조건 의존성 미반영.\n"
        f"- AD 외부 분자에 대한 예측은 외삽이며 신뢰도 낮음.\n\n"
    )

    full_md = header + abstract + intro + methods + results + conclusion + limitations

    return {
        "abstract":     abstract,
        "intro":        intro,
        "hypothesis":   "*generic 템플릿에는 별도 가설 섹션 없음.*",
        "methods":      methods,
        "results":      results,
        "hypothesis_val": "*generic 템플릿에는 별도 가설 검증 섹션 없음.*",
        "conclusion":   conclusion,
        "limitations":  limitations,
        "full_md":      full_md,
    }


# ─────────────────────────────────────────────────────────────────────────────
def paper_to_docx(paper: dict, figures: dict | None = None) -> bytes:
    """간단한 docx 변환 — Markdown 전체를 본문으로 삽입."""
    from docx import Document
    doc = Document()
    for line in paper["full_md"].splitlines():
        if line.startswith("# "):
            doc.add_heading(line[2:].strip(), level=1)
        elif line.startswith("## "):
            doc.add_heading(line[3:].strip(), level=2)
        elif line.startswith("### "):
            doc.add_heading(line[4:].strip(), level=3)
        else:
            doc.add_paragraph(line)
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ─────────────────────────────────────────────────────────────────────────────
def generate_paper_figures(**kwargs) -> dict:
    """generic 템플릿은 그림 생성 생략 (Streamlit 화면 그림으로 충분)."""
    return {}
